### ISSUE TITLE
Create architectural overview

### ISSUE THREAD

**Issue by JakWai01** [JakWai01/chatscape#1]
- [x] Investigate what technologies are required/useful
- [x] Create architectural diagram
- [x] Create sequence diagram containing first implementation details (e.g. lambdas) to further deepen the technological understanding
- [x] Create project summary and description in order to be able to present it at the playback

**Comment by JakWai01** [comment]
# Cloud Architecture
## Infrastructure
- https://sst.dev/ (drawback: Requires the Node ecosystem)
- https://www.terraform.io/
- https://kubernetes.io/

## AWS Services
- https://aws.amazon.com/de/ec2/ (Basis)
- https://aws.amazon.com/de/rds/ (Relationale Datenbank)
- https://aws.amazon.com/de/sns/ (Push Notification)
- https://aws.amazon.com/de/sqs/ (Queue Service for Messages)
- https://aws.amazon.com/de/api-gateway/ (Wenn sinnvoll)
- https://aws.amazon.com/de/cloudfront/ (CDN, to upload images)
- https://aws.amazon.com/de/elasticache/ (Falls wir Caching verwenden wollen)

## Software Architecture
- https://github.com/aws-samples/aws-lambda-hexagonal-architecture (Hexagonal architecture)
- Focus on testing and CI/CD

## Architectural Diagram
Create diagram using https://github.com/mermaid-js/mermaid: 
- Infrastructure as a Service (e.g. terraform, sst)
- Infrastructure (e.g. K8s cluster)
- OAuth2 authentication
- Web Page with GUI (Frontend)
- Lambdas
- Send_message
- Upload_image
- AWS s3 bucket
- CDN for images
- Cache before CDN? (redis instance on k8s)
- GitHub CI/CD
- [Tekton](https://tekton.dev/) 

## Storage
- Why do we need to store data? (Depends on our use-case)
  - Persist chat history in S3 bucket
  - Persist images in CDN

## Questions
- How do we receive messages using Lambdas (how do events work)?
  - This can be achieved by using [triggers](https://docs.aws.amazon.com/lambda/latest/dg/lambda-invocation.html) 
- Does it make sense to use just AWS services or should we also use a kubernetes cluster (maybe on AWS) for some services?

## Further Reading
- https://towardsdatascience.com/aws-lambda-7-things-i-wished-someone-told-me-63ec2021a772

**Comment by JakWai01** [comment]
# High Level System Design

A high level system design diagram displaying the *necessary* components for the system could look like the diagram below. 
**Note**: This graph is not final and should just serve as an initial diagram to kickstart further discussions on the system design. Futhermore, this project should be implemented using **hexagonal architecture**. [This](https://github.com/aws-samples/aws-lambda-hexagonal-architecture) is a guide on how this can be achieved using AWS. 

![Cloud Architecture](https://user-images.githubusercontent.com/59575534/234589277-f33080d2-e365-4ba9-928a-2c4e853e27d1.svg)

**Comment by JakWai01** [comment]
I think it would probably make sense to implement the **authentication** using a cloud service even in front of the loadbalancer in order to reduce the number of clients hitting the loadbalancer in the first place. Furthermore, we should probably use **DynamoDB** instead of redis since it's a service offered by AWS and seems to be equally benefitial. We should also think about **cache invalidation** e.g. when and how we delete images that haven't been accessed for a while (24h). Also, be aware that we don't have to put the whole logic for a usecase into a single lambda. We can use lambdas to call other lamdas to comply with principles such as **DRY** etc.

**Comment by JakWai01** [comment]
# Lambdas

This post can be used to discuss what lambas we actually need. 

- `upload_image`
   - `push_image`
- `invalidate_data`
  - `invalidate_images`
  - `invalidate_chat` (optional)
- `send_message`
   - `validate message` (optional)
   - `push_message`

Is it reasonable to just receive messages by reading the updates from the cache/S3 once `receive_message` was called? This is probably a pretty simple solution but could lead to very bad scaling and performance. Or maybe there's an option to use streams for the messages.

**Comment by JakWai01** [comment]
# Project Summary - ChatScape (WIP)

ChatScape is a simple cloud-native chat application. It allows for sending and receiving messages to and from a public channel as well as exchanging images on said channel. It is designed to be as primitive as possible while still requiring the developers to manage state and thereby creating some complexity when designing the system. 

In order to implement this system, the team will try to stick to using AWS whenever useful with the goal of mostly sticking to one coherent ecosystem.

**Comment by dentremor** [comment]
First of all, thank you for the work and concepts - nice job. :)

Some thoughts and questions:

- Should we mention the other AWS services (SNS, SQS, etc.) on the diagram also on the layer of S3, Redis, and CloudFront?
- Assuming that DynamoDB and AWS RDS are different services, it would be a good idea to have a discussion to determine which one is better suited for your needs. 
- Good idea with the load balancer - I think that makes sense.

**Comment by JakWai01** [comment]
I would definitely mention all of the AWS services including more detailed descriptions of the lambdas in a more sophisticated system design diagram. I am still not sure whether we need all those services thought. That's why I decided to not include them in the *high level* overview. 

I think that DynamoDB is rather a redis replacement and therefore has little to do with AWS RDS. I am unsure whether we want to use AWS RDS or just an S3 bucket. Currently, I would lean towards S3. But feel free to convince me of using RDS 😄

**Comment by JakWai01** [comment]
# System architecture diagram

This diagram is again just a draft to get the discussion started. I was hesitant to integrate any new components into the diagram and did also not quite finalize the lambda design. The reason for that is 1) my lack of experience using lambdas and 2) that I want to discuss the design choices with the rest of the development team. Still, this diagram shows a possible application flow and the required components:

<img width="476" alt="Screenshot 2023-04-26 at 16 27 33" src="https://user-images.githubusercontent.com/59575534/234694600-053f833d-f499-427d-bf19-b0c6a6b9de8d.png">

**Comment by dentremor** [comment]
As far as I know, DynamoDB is a NoSQL DB and a bit better suited for scaling, so it would make sense. But my knowledge in this area is quite limited, so further input might be quite useful. 😅

We should also evaluate if we want to use ElastiCache to get a better performance. :)

**Comment by pojntfx** [comment]
Here is my architecture proposal; this should also handle Authn, push notifications etc.:

![image](https://user-images.githubusercontent.com/28832235/235987942-474831b9-f0d6-4e25-8907-e96fa4e803a2.png)

- Store the SPA in a S3 bucket served by Cloudfront
- Let Route53 handle DNS for us
- Expose functions like `createMessage`, `listUsers` through API gateway
- Use S3 for chat blob storage
- Store chat history, profile metadata in RDS (or DynamoDB, personally I tend to prefer RDS since we can use any standard SQL client)
- Handle push notifications via AppSync & AWS SNS
- Use a SQS queue to handle internal events, e.g. to trigger the push notifications handler lambda when a message was sent
- Use AWS Cognito & the Amplify SDK for easy SPA Authn

... and a few more things (see the diagram)
